import {
  convertCase,
  type CodeGenerator,
  type Constant,
  type Field,
  type Module,
  type RecordKey,
  type RecordLocation,
} from "skir-internal";
import { z } from "zod";
import {
  getTypeName,
  modulePathToCsharpPath,
  modulePathToNamespace,
  toFieldPropertyName,
  toVariantTypeName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

class CsharpCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-csharp-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const outputFiles: CodeGenerator.OutputFile[] = [];
    for (const module of input.modules) {
      outputFiles.push({
        path: modulePathToCsharpPath(module.path),
        code: new CsharpSourceFileGenerator(
          module,
          modulePathToNamespace(module.path),
          input.recordMap,
        ).generate(),
      });
    }
    return { files: outputFiles };
  }
}

// Generates the code for one C# source file.
class CsharpSourceFileGenerator {
  private readonly lines: string[] = [];
  private readonly typeSpeller: TypeSpeller;

  constructor(
    private readonly module: Module,
    private readonly namespace: string,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
  ) {
    this.typeSpeller = new TypeSpeller(recordMap, module.path);
  }

  generate(): string {
    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.lines.push(
      "//  ______                        _               _  _  _",
      "//  |  _  \\                      | |             | |(_)| |",
      "//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_",
      "//  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _` || || __|",
      "//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_ ",
      "//  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|",
      "//",
      "// Generated by skir-csharp-gen",
      "// Home: https://github.com/gepheum/skir-csharp-gen",
      "",
      `namespace ${this.namespace};`,
      "",
    );

    // Emit all records defined in this module. Nested Skir records are emitted
    // as top-level C# types with flattened names (e.g. Outer_Inner).
    const moduleRecords = this.module.records.filter(
      (r) => r.modulePath === this.module.path,
    );

    for (const record of moduleRecords) {
      this.writeRecord(record, 0);
    }

    // Emit module-level constants (if any).
    this.writeModuleConstants();

    // Emit the per-module lazy initializer that wires all adapters.
    this.lines.push(`// ${"=".repeat(76)}`);
    this.lines.push("// Module initialization");
    this.lines.push(`// ${"=".repeat(76)}`);
    this.lines.push("");
    this.lines.push("internal static class ModuleInit_");
    this.lines.push("{");
    this.lines.push(
      "    private static readonly global::System.Lazy<bool> _lazy = new(() =>",
    );
    this.lines.push("    {");
    for (const record of moduleRecords) {
      const fqn = this.getFullyQualifiedTypeName(record);
      this.lines.push(`        ${fqn}.InitAdapter_();`);
    }
    this.lines.push("        return true;");
    this.lines.push("    });");
    this.lines.push(
      "    internal static void EnsureInit() => _ = _lazy.Value;",
    );
    this.lines.push("}");

    return this.lines.join("\n");
  }

  /** Emits a public static class `Consts` containing all module-level constants. */
  private writeModuleConstants(): void {
    const constants = this.module.constants.filter(
      (
        c,
      ): c is Constant & {
        type: NonNullable<Constant["type"]>;
        valueAsDenseJson: NonNullable<Constant["valueAsDenseJson"]>;
      } => c.type !== undefined && c.valueAsDenseJson !== undefined,
    );
    if (constants.length === 0) return;

    this.lines.push(`// ${"=".repeat(76)}`);
    this.lines.push("// Module constants");
    this.lines.push(`// ${"=".repeat(76)}`);
    this.lines.push("");
    this.lines.push("public static class Consts");
    this.lines.push("{");

    for (const constant of constants) {
      const propName = convertCase(constant.name.text, "UpperCamel");
      const type = constant.type;
      const csharpType = this.typeSpeller.getCsharpType(type);
      const serExpr = this.typeSpeller.getSerializerExpr(type, false);
      // Serialize the DenseJson value to a JSON string, then wrap it in a C#
      // string literal by JSON-stringifying the result (escaping special chars).
      const jsonLiteral = JSON.stringify(
        JSON.stringify(constant.valueAsDenseJson),
      );
      const lazyField = `_${propName.charAt(0).toLowerCase()}${propName.slice(1)}_Lazy`;

      this.lines.push(
        `    private static readonly global::System.Lazy<${csharpType}> ${lazyField}`,
      );
      this.lines.push(
        `        = new(() => ${serExpr}.FromJson(${jsonLiteral}));`,
      );
      this.lines.push(
        `    public static ${csharpType} ${propName} => ${lazyField}.Value;`,
      );
      this.lines.push("");
    }

    this.lines.push("}");
    this.lines.push("");
  }

  private writeRecord(record: RecordLocation, indentLevel: number): void {
    const indent = "    ".repeat(indentLevel);
    const name = getTypeName(record);
    const { recordType } = record.record;

    this.lines.push(`${indent}// ${"=".repeat(76)}`);
    this.lines.push(
      `${indent}// ${recordType} ${record.recordAncestors.map((r) => r.name.text).join(".")}`,
    );
    this.lines.push(`${indent}// ${"=".repeat(76)}`);
    this.lines.push("");

    if (recordType === "struct") {
      this.writeStruct(record, name, indentLevel);
    } else {
      this.writeEnum(record, name, indentLevel);
    }
    this.lines.push("");
  }

  private writeStruct(
    record: RecordLocation,
    name: string,
    indentLevel: number,
  ): void {
    const indent = "    ".repeat(indentLevel);
    const bodyIndent = "    ".repeat(indentLevel + 1);
    const body2Indent = "    ".repeat(indentLevel + 2);

    const fqName = this.getFullyQualifiedTypeName(record);
    const qualifiedName = record.recordAncestors
      .map((r) => r.name.text)
      .join(".");
    const modulePath = record.modulePath;

    this.lines.push(`${indent}public readonly record struct ${name}`);
    this.lines.push(`${indent}{`);

    // Pre-compute property names to reuse in both field declarations and InitAdapter_.
    const fieldInfos = this.computeFieldInfos(record, name);

    // Collect field info for DEFAULT init, Builder_, and the build lambda.
    const fieldDefaults: Array<{ propertyName: string; defaultExpr: string }> =
      [];

    for (const { field, propertyName } of fieldInfos) {
      const fieldType = this.typeSpeller.getCsharpFieldType(field);
      const defaultExpr = this.typeSpeller.getFieldDefaultExpr(field);

      this.lines.push(
        `${bodyIndent}public required ${fieldType} ${propertyName} { get; init; }`,
      );
      fieldDefaults.push({ propertyName, defaultExpr });
    }

    if (fieldInfos.length > 0) {
      this.lines.push("");
    }

    this.lines.push(
      `${bodyIndent}private global::SkirClient.Internal.UnrecognizedFields<${name}>? _unrecognized { get; init; }`,
    );
    const defaultInit =
      fieldDefaults.length > 0
        ? `new() { ${fieldDefaults.map((f) => `${f.propertyName} = ${f.defaultExpr}`).join(", ")} }`
        : "new()";
    this.lines.push(
      `${bodyIndent}public static readonly ${name} DEFAULT = ${defaultInit};`,
    );
    this.lines.push("");

    // Nested builder class.
    this.lines.push(`${bodyIndent}private sealed class Builder_`);
    this.lines.push(`${bodyIndent}{`);
    for (const { field, propertyName } of fieldInfos) {
      const fieldType = this.typeSpeller.getCsharpFieldType(field);
      const defaultExpr = this.typeSpeller.getFieldDefaultExpr(field);
      this.lines.push(
        `${body2Indent}public ${fieldType} ${propertyName} { get; set; } = ${defaultExpr};`,
      );
    }
    this.lines.push(
      `${body2Indent}public global::SkirClient.Internal.UnrecognizedFields<${fqName}>? _unrecognized { get; set; } = null;`,
    );
    this.lines.push(`${bodyIndent}}`);
    this.lines.push("");

    // Adapter field.
    const newBuilderLambda = "() => new Builder_()";
    const buildFields = fieldDefaults
      .map((f) => `${f.propertyName} = b.${f.propertyName}`)
      .join(", ");
    const buildLambda = buildFields
      ? `b => new ${name} { ${buildFields}, _unrecognized = b._unrecognized }`
      : `b => new ${name} { _unrecognized = b._unrecognized }`;
    this.lines.push(
      `${bodyIndent}private static readonly global::SkirClient.StructAdapter<${fqName}, Builder_> _adapter =`,
    );
    this.lines.push(
      `${bodyIndent}    new(${name}.DEFAULT, ${JSON.stringify(modulePath)}, ${JSON.stringify(qualifiedName)},`,
    );
    this.lines.push(`${bodyIndent}        ${newBuilderLambda},`);
    this.lines.push(`${bodyIndent}        ${buildLambda},`);
    this.lines.push(`${bodyIndent}        x => x._unrecognized,`);
    this.lines.push(`${bodyIndent}        (b, v) => b._unrecognized = v);`);
    this.lines.push(
      `${bodyIndent}internal static readonly global::SkirClient.Serializer<${fqName}> _adapterSerializer = new(_adapter);`,
    );
    this.lines.push("");

    // Serializer property.
    this.lines.push(
      `${bodyIndent}public static global::SkirClient.Serializer<${fqName}> Serializer`,
    );
    this.lines.push(
      `${bodyIndent}{ get { ModuleInit_.EnsureInit(); return _adapterSerializer; } }`,
    );
    this.lines.push("");

    // InitAdapter_ method.
    this.lines.push(`${bodyIndent}internal static void InitAdapter_()`);
    this.lines.push(`${bodyIndent}{`);

    for (const removedNumber of record.record.removedNumbers) {
      this.lines.push(
        `${body2Indent}_adapter.AddRemovedNumber(${removedNumber});`,
      );
    }

    for (const { field, propertyName } of fieldInfos) {
      const serExpr = this.typeSpeller.getSerializerExpr(
        field.type!,
        true,
        field.isRecursive,
      );
      const getter = this.makeStructFieldGetter(field, propertyName);
      const setter = this.makeStructFieldSetter(field, propertyName);
      this.lines.push(
        `${body2Indent}_adapter.AddField(${JSON.stringify(field.name.text)}, ${field.number}, ${serExpr},`,
      );
      this.lines.push(`${body2Indent}    ${getter},`);
      this.lines.push(`${body2Indent}    ${setter});`);
    }

    this.lines.push(`${body2Indent}_adapter.Finalize_();`);
    this.lines.push(`${bodyIndent}}`);
    this.lines.push(`${indent}}`);
  }

  private writeEnum(
    record: RecordLocation,
    name: string,
    indentLevel: number,
  ): void {
    const indent = "    ".repeat(indentLevel);
    const bodyIndent = "    ".repeat(indentLevel + 1);
    const body2Indent = "    ".repeat(indentLevel + 2);
    const body3Indent = "    ".repeat(indentLevel + 3);
    const variants = record.record.fields;

    const fqBase = this.getFullyQualifiedTypeName(record);
    const qualifiedName = record.recordAncestors
      .map((r) => r.name.text)
      .join(".");
    const modulePath = record.modulePath;

    // Reserved names within the enum body: UNKNOWN is always synthesized, and
    // the enum name itself must not be reused (CS0542-equivalent for records).
    const reservedVariantNames = new Set<string>([
      "UNKNOWN",
      "DEFAULT",
      "Serializer",
      "InitAdapter_",
      "_adapter",
      "_adapterSerializer",
      name,
    ]);

    // Pre-compute variant type names to reuse in declarations and InitAdapter_.
    const variantInfos = variants.map((v) => ({
      variant: v,
      typeName: toVariantTypeName(v, reservedVariantNames),
    }));

    this.lines.push(`${indent}public abstract record ${name}`);
    this.lines.push(`${indent}{`);

    // UNKNOWN variant: use explicit body (not positional) to avoid CS8910
    // (primary constructor conflicts with synthesized copy constructor).
    this.lines.push(`${bodyIndent}public sealed record UNKNOWN : ${fqBase}`);
    this.lines.push(`${bodyIndent}{`);
    this.lines.push(
      `${body2Indent}public global::SkirClient.Internal.UnrecognizedVariant<${fqBase}>? Value { get; init; } = null;`,
    );
    this.lines.push(`${bodyIndent}}`);
    if (variantInfos.length > 0) {
      const firstVariant = variantInfos[0]!;
      const defaultExpr = firstVariant.variant.type
        ? `new ${firstVariant.typeName} { Value = ${this.typeSpeller.getDefaultExpr(firstVariant.variant.type)} }`
        : `new ${firstVariant.typeName}()`;
      this.lines.push(
        `${bodyIndent}public static ${name} DEFAULT { get; } = ${defaultExpr};`,
      );
    } else {
      this.lines.push(
        `${bodyIndent}public static ${name} DEFAULT { get; } = new UNKNOWN();`,
      );
    }

    if (variantInfos.length > 0) {
      this.lines.push("");
    }

    for (const { variant, typeName } of variantInfos) {
      if (variant.type) {
        const payloadType = this.typeSpeller.getCsharpType(variant.type);
        const defaultExpr = this.typeSpeller.getDefaultExpr(variant.type);
        // Use explicit body (not positional constructor) to avoid CS8910.
        this.lines.push(
          `${bodyIndent}public sealed record ${typeName} : ${fqBase}`,
        );
        this.lines.push(`${bodyIndent}{`);
        this.lines.push(
          `${body2Indent}public ${payloadType} Value { get; init; } = ${defaultExpr};`,
        );
        this.lines.push(`${bodyIndent}}`);
      } else {
        this.lines.push(
          `${bodyIndent}public sealed record ${typeName} : ${fqBase};`,
        );
      }
    }

    this.lines.push("");

    // Adapter field.
    this.lines.push(
      `${bodyIndent}internal static readonly global::SkirClient.EnumAdapter<${fqBase}> _adapter =`,
    );
    this.lines.push(`${bodyIndent}    new(`);
    this.lines.push(`${body2Indent}x => x switch {`);
    this.lines.push(`${body3Indent}${fqBase}.UNKNOWN _ => 0,`);
    variantInfos.forEach(({ typeName }, i) => {
      this.lines.push(`${body3Indent}${fqBase}.${typeName} _ => ${i + 1},`);
    });
    this.lines.push(`${body3Indent}_ => 0`);
    this.lines.push(`${body2Indent}},`);
    this.lines.push(`${body2Indent}u => new ${fqBase}.UNKNOWN { Value = u },`);
    this.lines.push(
      `${body2Indent}x => x is ${fqBase}.UNKNOWN _u ? _u.Value : null,`,
    );
    this.lines.push(`${body2Indent}${name}.DEFAULT,`);
    this.lines.push(`${body2Indent}${JSON.stringify(modulePath)},`);
    this.lines.push(`${body2Indent}${JSON.stringify(qualifiedName)});`);
    this.lines.push(
      `${bodyIndent}internal static readonly global::SkirClient.Serializer<${fqBase}> _adapterSerializer = new(_adapter);`,
    );
    this.lines.push("");

    // Serializer property.
    this.lines.push(
      `${bodyIndent}public static global::SkirClient.Serializer<${fqBase}> Serializer`,
    );
    this.lines.push(
      `${bodyIndent}{ get { ModuleInit_.EnsureInit(); return _adapterSerializer; } }`,
    );
    this.lines.push("");

    // InitAdapter_ method.
    this.lines.push(`${bodyIndent}internal static void InitAdapter_()`);
    this.lines.push(`${bodyIndent}{`);

    for (const removedNumber of record.record.removedNumbers) {
      this.lines.push(
        `${body2Indent}_adapter.AddRemovedNumber(${removedNumber});`,
      );
    }

    variantInfos.forEach(({ variant, typeName }, i) => {
      const kindOrdinal = i + 1;
      if (variant.type) {
        const payloadCsharpType = this.typeSpeller.getCsharpType(variant.type);
        const serExpr = this.typeSpeller.getSerializerExpr(variant.type, true);
        this.lines.push(
          `${body2Indent}_adapter.AddWrapperVariant<${payloadCsharpType}>(${JSON.stringify(variant.name.text)}, ${variant.number}, ${kindOrdinal},`,
        );
        this.lines.push(`${body3Indent}${serExpr},`);
        this.lines.push(
          `${body3Indent}v => new ${fqBase}.${typeName} { Value = v },`,
        );
        this.lines.push(
          `${body3Indent}x => ((${fqBase}.${typeName})x).Value);`,
        );
      } else {
        this.lines.push(
          `${body2Indent}_adapter.AddConstantVariant(${JSON.stringify(variant.name.text)}, ${variant.number}, ${kindOrdinal}, new ${fqBase}.${typeName}());`,
        );
      }
    });

    this.lines.push(`${body2Indent}_adapter.Finalize_();`);
    this.lines.push(`${bodyIndent}}`);
    this.lines.push(`${indent}}`);
  }

  /**
   * Pre-computes (field, propertyName) pairs for a struct, applying the same
   * collision-avoidance logic in both the field declaration and InitAdapter_.
   */
  private computeFieldInfos(
    record: RecordLocation,
    typeName: string,
  ): Array<{ field: Field; propertyName: string }> {
    const result: Array<{ field: Field; propertyName: string }> = [];
    const usedNames = new Set<string>([
      "DEFAULT",
      "Serializer",
      "InitAdapter_",
      "_adapter",
      "_adapterSerializer",
      "_unrecognized",
    ]);
    for (const field of record.record.fields) {
      if (!field.type) continue;
      let propertyName = toFieldPropertyName(field, typeName);
      while (usedNames.has(propertyName) || propertyName === typeName) {
        propertyName = `${propertyName}_`;
      }
      usedNames.add(propertyName);
      result.push({ field, propertyName });
    }
    return result;
  }

  /** Returns a lambda expression `x => …` that retrieves the field value. */
  private makeStructFieldGetter(_field: Field, propertyName: string): string {
    return `x => x.${propertyName}`;
  }

  /** Returns a lambda expression `(b, v) => …` that sets the field value on the builder. */
  private makeStructFieldSetter(_field: Field, propertyName: string): string {
    return `(b, v) => b.${propertyName} = v`;
  }

  /** Returns the fully-qualified C# type name for a record, e.g.
   * global::Skirout.Enums.Weekday or global::Skirout.Enums.Kind */
  private getFullyQualifiedTypeName(record: RecordLocation): string {
    const ns = modulePathToNamespace(record.modulePath);
    const typePath = getTypeName(record);
    return `global::${ns}.${typePath}`;
  }
}

export const GENERATOR = new CsharpCodeGenerator();
