import {
  convertCase,
  type CodeGenerator,
  type Constant,
  type Field,
  type Module,
  type RecordKey,
  type RecordLocation,
} from "skir-internal";
import { z } from "zod";
import {
  getTypeName,
  modulePathToCsharpPath,
  modulePathToNamespace,
  toFieldPropertyName,
  toVariantTypeName,
} from "./naming.js";
import { TypeSpeller } from "./type_speller.js";

const Config = z.strictObject({});

type Config = z.infer<typeof Config>;

class CsharpCodeGenerator implements CodeGenerator<Config> {
  readonly id = "skir-csharp-gen";
  readonly configType = Config;

  generateCode(input: CodeGenerator.Input<Config>): CodeGenerator.Output {
    const outputFiles: CodeGenerator.OutputFile[] = [];
    for (const module of input.modules) {
      outputFiles.push({
        path: modulePathToCsharpPath(module.path),
        code: new CsharpSourceFileGenerator(
          module,
          modulePathToNamespace(module.path),
          input.recordMap,
        ).generate(),
      });
    }
    return { files: outputFiles };
  }
}

// Generates the code for one C# source file.
class CsharpSourceFileGenerator {
  private readonly lines: string[] = [];
  private readonly typeSpeller: TypeSpeller;

  constructor(
    private readonly module: Module,
    private readonly namespace: string,
    recordMap: ReadonlyMap<RecordKey, RecordLocation>,
  ) {
    this.typeSpeller = new TypeSpeller(recordMap, module.path);
  }

  generate(): string {
    // http://patorjk.com/software/taag/#f=Doom&t=Do%20not%20edit
    this.lines.push(
      "//  ______                        _               _  _  _",
      "//  |  _  \\                      | |             | |(_)| |",
      "//  | | | |  ___    _ __    ___  | |_    ___   __| | _ | |_",
      "//  | | | | / _ \\  | '_ \\  / _ \\ | __|  / _ \\ / _` || || __|",
      "//  | |/ / | (_) | | | | || (_) || |_  |  __/| (_| || || |_ ",
      "//  |___/   \\___/  |_| |_| \\___/  \\__|  \\___| \\__,_||_| \\__|",
      "//",
      "// Generated by skir-csharp-gen",
      "// Home: https://github.com/gepheum/skir-csharp-gen",
      "",
      `namespace ${this.namespace};`,
      "",
    );

    // Emit all records defined in this module. Nested Skir records are emitted
    // as top-level C# types with flattened names (e.g. Outer_Inner).
    const moduleRecords = this.module.records.filter(
      (r) => r.modulePath === this.module.path,
    );

    for (const record of moduleRecords) {
      this.writeRecord(record, 0);
    }

    // Emit module-level constants (if any).
    this.writeModuleConstants();

    // Emit the per-module lazy initializer that wires all adapters.
    this.lines.push(`// ${"=".repeat(76)}`);
    this.lines.push("// Module initialization");
    this.lines.push(`// ${"=".repeat(76)}`);
    this.lines.push("");
    this.lines.push("internal static class ModuleInit_");
    this.lines.push("{");
    this.lines.push(
      "    private static readonly global::System.Lazy<bool> _lazy = new(() =>",
    );
    this.lines.push("    {");
    for (const record of moduleRecords) {
      const fqn = this.getFullyQualifiedTypeName(record);
      this.lines.push(`        ${fqn}.InitAdapter_();`);
    }
    this.lines.push("        return true;");
    this.lines.push("    });");
    this.lines.push(
      "    internal static void EnsureInit() => _ = _lazy.Value;",
    );
    this.lines.push("}");

    return this.lines.join("\n");
  }

  /** Emits a public static class `Consts` containing all module-level constants. */
  private writeModuleConstants(): void {
    const constants = this.module.constants.filter(
      (
        c,
      ): c is Constant & {
        type: NonNullable<Constant["type"]>;
        valueAsDenseJson: NonNullable<Constant["valueAsDenseJson"]>;
      } => c.type !== undefined && c.valueAsDenseJson !== undefined,
    );
    if (constants.length === 0) return;

    this.lines.push(`// ${"=".repeat(76)}`);
    this.lines.push("// Module constants");
    this.lines.push(`// ${"=".repeat(76)}`);
    this.lines.push("");
    this.lines.push("public static class Consts");
    this.lines.push("{");

    for (const constant of constants) {
      const propName = convertCase(constant.name.text, "UpperCamel");
      const type = constant.type;
      const csharpType = this.typeSpeller.getCsharpType(type);
      const serExpr = this.typeSpeller.getSerializerExpr(type, false);
      // Serialize the DenseJson value to a JSON string, then wrap it in a C#
      // string literal by JSON-stringifying the result (escaping special chars).
      const jsonLiteral = JSON.stringify(
        JSON.stringify(constant.valueAsDenseJson),
      );
      const lazyField = `_${propName.charAt(0).toLowerCase()}${propName.slice(1)}_Lazy`;

      this.lines.push(
        `    private static readonly global::System.Lazy<${csharpType}> ${lazyField}`,
      );
      this.lines.push(
        `        = new(() => ${serExpr}.FromJson(${jsonLiteral}));`,
      );
      this.lines.push(
        `    public static ${csharpType} ${propName} => ${lazyField}.Value;`,
      );
      this.lines.push("");
    }

    this.lines.push("}");
    this.lines.push("");
  }

  private writeRecord(record: RecordLocation, indentLevel: number): void {
    const indent = "    ".repeat(indentLevel);
    const name = getTypeName(record);
    const { recordType } = record.record;

    this.lines.push(`${indent}// ${"=".repeat(76)}`);
    this.lines.push(
      `${indent}// ${recordType} ${record.recordAncestors.map((r) => r.name.text).join(".")}`,
    );
    this.lines.push(`${indent}// ${"=".repeat(76)}`);
    this.lines.push("");

    if (recordType === "struct") {
      this.writeStruct(record, name, indentLevel);
    } else {
      this.writeEnum(record, name, indentLevel);
    }
    this.lines.push("");
  }

  private writeStruct(
    record: RecordLocation,
    name: string,
    indentLevel: number,
  ): void {
    const indent = "    ".repeat(indentLevel);
    const bodyIndent = "    ".repeat(indentLevel + 1);
    const body2Indent = "    ".repeat(indentLevel + 2);

    const fqName = this.getFullyQualifiedTypeName(record);
    const qualifiedName = record.recordAncestors
      .map((r) => r.name.text)
      .join(".");
    const modulePath = record.modulePath;

    this.lines.push(`${indent}public readonly record struct ${name}`);
    this.lines.push(`${indent}{`);

    // Pre-compute property names to reuse in both field declarations and InitAdapter_.
    const fieldInfos = this.computeFieldInfos(record, name);

    // Collect field info for Default init, Builder_, and the build lambda.
    const fieldDefaults: Array<{ propertyName: string; defaultExpr: string }> =
      [];

    for (const { field, propertyName } of fieldInfos) {
      const fieldType = this.typeSpeller.getCsharpFieldType(field);
      const defaultExpr = this.typeSpeller.getFieldDefaultExpr(field);

      this.lines.push(
        `${bodyIndent}public required ${fieldType} ${propertyName} { get; init; }`,
      );
      fieldDefaults.push({ propertyName, defaultExpr });
    }

    if (fieldInfos.length > 0) {
      this.lines.push("");
    }

    this.lines.push(
      `${bodyIndent}private global::SkirClient.Internal.UnrecognizedFields<${name}>? _unrecognized { get; init; }`,
    );
    const defaultInit =
      fieldDefaults.length > 0
        ? `new() { ${fieldDefaults.map((f) => `${f.propertyName} = ${f.defaultExpr}`).join(", ")} }`
        : "new()";
    this.lines.push(
      `${bodyIndent}public static readonly ${name} Default = ${defaultInit};`,
    );
    this.lines.push("");

    // Nested builder class.
    this.lines.push(`${bodyIndent}private sealed class Builder_`);
    this.lines.push(`${bodyIndent}{`);
    for (const { field, propertyName } of fieldInfos) {
      const fieldType = this.typeSpeller.getCsharpFieldType(field);
      const defaultExpr = this.typeSpeller.getFieldDefaultExpr(field);
      this.lines.push(
        `${body2Indent}public ${fieldType} ${propertyName} { get; set; } = ${defaultExpr};`,
      );
    }
    this.lines.push(
      `${body2Indent}public global::SkirClient.Internal.UnrecognizedFields<${fqName}>? _unrecognized { get; set; } = null;`,
    );
    this.lines.push(`${bodyIndent}}`);
    this.lines.push("");

    // Adapter field.
    const newBuilderLambda = "() => new Builder_()";
    const buildFields = fieldDefaults
      .map((f) => `${f.propertyName} = b.${f.propertyName}`)
      .join(", ");
    const buildLambda = buildFields
      ? `b => new ${name} { ${buildFields}, _unrecognized = b._unrecognized }`
      : `b => new ${name} { _unrecognized = b._unrecognized }`;
    const structDoc = this.getDocText(record.record.doc);
    this.lines.push(
      `${bodyIndent}private static readonly global::SkirClient.Internal.StructAdapter<${fqName}, Builder_> _adapter =`,
    );
    this.lines.push(
      `${bodyIndent}    new(${name}.Default, ${JSON.stringify(modulePath)}, ${JSON.stringify(qualifiedName)}, ${JSON.stringify(structDoc)},`,
    );
    this.lines.push(`${bodyIndent}        ${newBuilderLambda},`);
    this.lines.push(`${bodyIndent}        ${buildLambda},`);
    this.lines.push(`${bodyIndent}        x => x._unrecognized,`);
    this.lines.push(`${bodyIndent}        (b, v) => b._unrecognized = v);`);
    this.lines.push(
      `${bodyIndent}internal static readonly global::SkirClient.Serializer<${fqName}> _adapterSerializer = new(_adapter);`,
    );
    this.lines.push("");

    // Serializer property.
    this.lines.push(
      `${bodyIndent}public static global::SkirClient.Serializer<${fqName}> Serializer`,
    );
    this.lines.push(
      `${bodyIndent}{ get { ModuleInit_.EnsureInit(); return _adapterSerializer; } }`,
    );
    this.lines.push("");

    // InitAdapter_ method.
    this.lines.push(`${bodyIndent}internal static void InitAdapter_()`);
    this.lines.push(`${bodyIndent}{`);

    for (const removedNumber of record.record.removedNumbers) {
      this.lines.push(
        `${body2Indent}_adapter.AddRemovedNumber(${removedNumber});`,
      );
    }

    for (const { field, propertyName } of fieldInfos) {
      const serExpr = this.typeSpeller.getSerializerExpr(
        field.type!,
        true,
        field.isRecursive,
      );
      const getter = this.makeStructFieldGetter(field, propertyName);
      const setter = this.makeStructFieldSetter(field, propertyName);
      this.lines.push(
        `${body2Indent}_adapter.AddField(${JSON.stringify(field.name.text)}, ${field.number}, ${serExpr},`,
      );
      this.lines.push(`${body2Indent}    ${getter},`);
      this.lines.push(
        `${body2Indent}    ${setter}, ${JSON.stringify(this.getDocText(field.doc))});`,
      );
    }

    this.lines.push(`${body2Indent}_adapter.Finalize_();`);
    this.lines.push(`${bodyIndent}}`);
    this.lines.push(`${indent}}`);
  }

  private writeEnum(
    record: RecordLocation,
    name: string,
    indentLevel: number,
  ): void {
    const indent = "    ".repeat(indentLevel);
    const bodyIndent = "    ".repeat(indentLevel + 1);
    const body2Indent = "    ".repeat(indentLevel + 2);
    const body3Indent = "    ".repeat(indentLevel + 3);
    const variants = record.record.fields;

    const fqBase = this.getFullyQualifiedTypeName(record);
    const kindTypeName = name === "KindType" ? "KindType_" : "KindType";
    const kindMemberName = name === "Kind" ? "Kind_" : "Kind";
    const kindMemberVisibility = name === "Kind" ? "private" : "public";
    const qualifiedName = record.recordAncestors
      .map((r) => r.name.text)
      .join(".");
    const modulePath = record.modulePath;

    // Pre-compute variant type names to reuse in declarations and InitAdapter_.
    const variantInfos = variants.map((v) => ({
      variant: v,
      memberName: toVariantTypeName(v),
      prefixedName: convertCase(v.name.text, "UpperCamel"),
    }));

    this.lines.push(`${indent}public sealed record ${name}`);
    this.lines.push(`${indent}{`);

    this.lines.push(`${bodyIndent}public enum ${kindTypeName}`);
    this.lines.push(`${bodyIndent}{`);
    this.lines.push(`${body2Indent}Unknown,`);
    variantInfos.forEach(({ variant }, i) => {
      const suffix = i < variantInfos.length - 1 ? "," : "";
      const upperCamel = convertCase(variant.name.text, "UpperCamel");
      const kindName = variant.type ? `${upperCamel}Wrapper` : upperCamel;
      this.lines.push(`${body2Indent}${kindName}${suffix}`);
    });
    this.lines.push(`${bodyIndent}}`);
    this.lines.push("");

    this.lines.push(
      `${bodyIndent}${kindMemberVisibility} ${kindTypeName} ${kindMemberName} { get; init; }`,
    );
    this.lines.push(`${bodyIndent}private object? Value_ { get; init; }`);
    this.lines.push("");

    this.lines.push(
      `${bodyIndent}private ${name}(${kindTypeName} kind, object? value)`,
    );
    this.lines.push(`${bodyIndent}{`);
    this.lines.push(`${body2Indent}this.${kindMemberName} = kind;`);
    this.lines.push(`${body2Indent}this.Value_ = value;`);
    this.lines.push(`${bodyIndent}}`);
    this.lines.push("");

    this.lines.push(
      `${bodyIndent}public static readonly ${fqBase} Unknown = new(${kindTypeName}.Unknown, null);`,
    );

    for (const { variant, memberName } of variantInfos) {
      if (!variant.type) {
        const upperCamel = convertCase(variant.name.text, "UpperCamel");
        const kindName = upperCamel;
        this.lines.push(
          `${bodyIndent}public static readonly ${fqBase} ${memberName} = new(${kindTypeName}.${kindName}, null);`,
        );
      }
    }

    if (variantInfos.length > 0) {
      this.lines.push("");
    }

    for (const { variant, prefixedName } of variantInfos) {
      if (!variant.type) {
        continue;
      }
      const payloadType = this.typeSpeller.getCsharpType(variant.type);
      const kindName = `${convertCase(variant.name.text, "UpperCamel")}Wrapper`;

      this.lines.push(
        `${bodyIndent}public static ${fqBase} Wrap${prefixedName}(${payloadType} value) => new(${kindTypeName}.${kindName}, value);`,
      );
      this.lines.push(`${bodyIndent}public ${payloadType} As${prefixedName}()`);
      this.lines.push(`${bodyIndent}{`);
      this.lines.push(
        `${body2Indent}if (${kindMemberName} != ${kindTypeName}.${kindName})`,
      );
      this.lines.push(
        `${body3Indent}throw new global::System.InvalidOperationException("kind=" + ${kindMemberName}.ToString());`,
      );
      this.lines.push(`${body2Indent}return (${payloadType})Value_!;`);
      this.lines.push(`${bodyIndent}}`);
      this.lines.push("");
    }

    this.lines.push(`${bodyIndent}public interface IVisitor<R>`);
    this.lines.push(`${bodyIndent}{`);
    this.lines.push(`${body2Indent}R OnUnknown();`);
    for (const { variant, prefixedName } of variantInfos) {
      if (variant.type) {
        const payloadType = this.typeSpeller.getCsharpType(variant.type);
        this.lines.push(
          `${body2Indent}R On${prefixedName}(${payloadType} value);`,
        );
      } else {
        this.lines.push(`${body2Indent}R On${prefixedName}();`);
      }
    }
    this.lines.push(`${bodyIndent}}`);
    this.lines.push("");

    this.lines.push(`${bodyIndent}public R Accept<R>(IVisitor<R> visitor)`);
    this.lines.push(`${bodyIndent}{`);
    this.lines.push(`${body2Indent}return ${kindMemberName} switch`);
    this.lines.push(`${body2Indent}{`);
    this.lines.push(
      `${body3Indent}${kindTypeName}.Unknown => visitor.OnUnknown(),`,
    );
    variantInfos.forEach(({ variant, prefixedName }) => {
      const upperCamel = convertCase(variant.name.text, "UpperCamel");
      const kindName = variant.type ? `${upperCamel}Wrapper` : upperCamel;
      if (variant.type) {
        this.lines.push(
          `${body3Indent}${kindTypeName}.${kindName} => visitor.On${prefixedName}(As${prefixedName}()),`,
        );
      } else {
        this.lines.push(
          `${body3Indent}${kindTypeName}.${kindName} => visitor.On${prefixedName}(),`,
        );
      }
    });
    this.lines.push(
      `${body3Indent}_ => throw new global::System.InvalidOperationException("kind=" + ${kindMemberName}.ToString())`,
    );
    this.lines.push(`${body2Indent}};`);
    this.lines.push(`${bodyIndent}}`);
    this.lines.push("");

    this.lines.push(`${bodyIndent}public bool Equals(${fqBase}? other)`);
    this.lines.push(`${bodyIndent}{`);
    this.lines.push(`${body2Indent}if (other is null) return false;`);
    this.lines.push(
      `${body2Indent}if (ReferenceEquals(this, other)) return true;`,
    );
    this.lines.push(
      `${body2Indent}if (${kindMemberName} != other.${kindMemberName}) return false;`,
    );
    this.lines.push(
      `${body2Indent}if (${kindMemberName} == ${kindTypeName}.Unknown) return true;`,
    );
    this.lines.push(
      `${body2Indent}return global::System.Collections.Generic.EqualityComparer<object?>.Default.Equals(Value_, other.Value_);`,
    );
    this.lines.push(`${bodyIndent}}`);
    this.lines.push("");

    this.lines.push(`${bodyIndent}public override int GetHashCode() =>`);
    this.lines.push(
      `${body2Indent}${kindMemberName} == ${kindTypeName}.Unknown ? 0 : global::System.HashCode.Combine(${kindMemberName}, Value_);`,
    );
    this.lines.push("");

    // Adapter field.
    const enumDoc = this.getDocText(record.record.doc);
    this.lines.push(
      `${bodyIndent}internal static readonly global::SkirClient.Internal.EnumAdapter<${fqBase}> _adapter =`,
    );
    this.lines.push(`${bodyIndent}    new(`);
    this.lines.push(`${body2Indent}x => x.${kindMemberName} switch`);
    this.lines.push(`${body2Indent}{`);
    this.lines.push(`${body3Indent}${fqBase}.${kindTypeName}.Unknown => 0,`);
    variantInfos.forEach(({ variant }, i) => {
      const upperCamel = convertCase(variant.name.text, "UpperCamel");
      const kindName = variant.type ? `${upperCamel}Wrapper` : upperCamel;
      this.lines.push(
        `${body3Indent}${fqBase}.${kindTypeName}.${kindName} => ${i + 1},`,
      );
    });
    this.lines.push(
      `${body3Indent}_ => throw new global::System.InvalidOperationException("kind=" + x.${kindMemberName}.ToString())`,
    );
    this.lines.push(`${body2Indent}},`);
    this.lines.push(
      `${body2Indent}u => new(${fqBase}.${kindTypeName}.Unknown, u),`,
    );
    this.lines.push(
      `${body2Indent}x => x.${kindMemberName} == ${fqBase}.${kindTypeName}.Unknown ? x.Value_ as global::SkirClient.Internal.UnrecognizedVariant<${fqBase}> : null,`,
    );
    this.lines.push(`${body2Indent}${fqBase}.Unknown,`);
    this.lines.push(`${body2Indent}${JSON.stringify(modulePath)},`);
    this.lines.push(`${body2Indent}${JSON.stringify(qualifiedName)},`);
    this.lines.push(`${body2Indent}${JSON.stringify(enumDoc)});`);
    this.lines.push(
      `${bodyIndent}internal static readonly global::SkirClient.Serializer<${fqBase}> _adapterSerializer = new(_adapter);`,
    );
    this.lines.push("");

    // Serializer property.
    this.lines.push(
      `${bodyIndent}public static global::SkirClient.Serializer<${fqBase}> Serializer`,
    );
    this.lines.push(
      `${bodyIndent}{ get { ModuleInit_.EnsureInit(); return _adapterSerializer; } }`,
    );
    this.lines.push("");

    // InitAdapter_ method.
    this.lines.push(`${bodyIndent}internal static void InitAdapter_()`);
    this.lines.push(`${bodyIndent}{`);

    for (const removedNumber of record.record.removedNumbers) {
      this.lines.push(
        `${body2Indent}_adapter.AddRemovedNumber(${removedNumber});`,
      );
    }

    variantInfos.forEach(({ variant, memberName, prefixedName }, i) => {
      const kindOrdinal = i + 1;
      if (variant.type) {
        const payloadCsharpType = this.typeSpeller.getCsharpType(variant.type);
        const serExpr = this.typeSpeller.getSerializerExpr(variant.type, true);
        this.lines.push(
          `${body2Indent}_adapter.AddWrapperVariant<${payloadCsharpType}>(${JSON.stringify(variant.name.text)}, ${variant.number}, ${kindOrdinal},`,
        );
        this.lines.push(`${body3Indent}${serExpr},`);
        this.lines.push(`${body3Indent}v => ${fqBase}.Wrap${prefixedName}(v),`);
        this.lines.push(
          `${body3Indent}x => x.As${prefixedName}(), ${JSON.stringify(this.getDocText(variant.doc))});`,
        );
      } else {
        this.lines.push(
          `${body2Indent}_adapter.AddConstantVariant(${JSON.stringify(variant.name.text)}, ${variant.number}, ${kindOrdinal}, ${fqBase}.${memberName}, ${JSON.stringify(this.getDocText(variant.doc))});`,
        );
      }
    });

    this.lines.push(`${body2Indent}_adapter.Finalize_();`);
    this.lines.push(`${bodyIndent}}`);
    this.lines.push(`${indent}}`);
  }

  /**
   * Pre-computes (field, propertyName) pairs for a struct, applying the same
   * collision-avoidance logic in both the field declaration and InitAdapter_.
   */
  private computeFieldInfos(
    record: RecordLocation,
    typeName: string,
  ): Array<{ field: Field; propertyName: string }> {
    const result: Array<{ field: Field; propertyName: string }> = [];
    const usedNames = new Set<string>([
      "Default",
      "DEFAULT",
      "Serializer",
      "InitAdapter_",
      "_adapter",
      "_adapterSerializer",
      "_unrecognized",
    ]);
    for (const field of record.record.fields) {
      if (!field.type) continue;
      let propertyName = toFieldPropertyName(field, typeName);
      while (usedNames.has(propertyName) || propertyName === typeName) {
        propertyName = `${propertyName}_`;
      }
      usedNames.add(propertyName);
      result.push({ field, propertyName });
    }
    return result;
  }

  /** Returns a lambda expression `x => …` that retrieves the field value. */
  private makeStructFieldGetter(_field: Field, propertyName: string): string {
    return `x => x.${propertyName}`;
  }

  /** Returns a lambda expression `(b, v) => …` that sets the field value on the builder. */
  private makeStructFieldSetter(_field: Field, propertyName: string): string {
    return `(b, v) => b.${propertyName} = v`;
  }

  private getDocText(doc: unknown): string {
    const pieces = (doc as { pieces?: readonly unknown[] } | undefined)?.pieces;
    if (!pieces || pieces.length === 0) {
      return "";
    }
    const text = pieces
      .map((piece) => {
        const p = piece as {
          kind?: string;
          text?: string;
          nameParts?: readonly { token?: { text?: string } }[];
        };
        if (p.kind === "text") {
          return p.text ?? "";
        }
        if (p.kind === "reference" && p.nameParts) {
          return p.nameParts
            .map((part) => part.token?.text ?? "")
            .filter((name) => name.length > 0)
            .join(".");
        }
        return "";
      })
      .join("")
      .trim();
    return text;
  }

  /** Returns the fully-qualified C# type name for a record, e.g.
   * global::Skirout.Enums.Weekday or global::Skirout.Enums.Kind */
  private getFullyQualifiedTypeName(record: RecordLocation): string {
    const ns = modulePathToNamespace(record.modulePath);
    const typePath = getTypeName(record);
    return `global::${ns}.${typePath}`;
  }
}

export const GENERATOR = new CsharpCodeGenerator();
